config/routes.rb
Rbms::Application.routes.draw do
  root :to => 'home#index', as: :homepage

  get '/movies/find' => 'movies#find'
  get '/movies/:id' => 'movies#show', as: :movies_show

  # mount Wungine::Engine, at: "weather", as: :wungine

end

app/models/actor.rb
class Actor < Hashie::Dash
	#general properties
	property :id, required: true
	property :name
	property :profile_path
end

app/models/carousel.rb
class Carousel < Hashie::Dash
  #general properties
  property :name
  property :lazy_load_resource
  property :tiles

  def lazy_load?
    !lazy_load_resource.nil?
  end

  def has_tiles?
    tiles.present?
  end
end

app/models/movie.rb
class Movie < Hashie::Dash
	#general properties
	property :id, required: true
	property :title
	property :release_date
	property :tagline
	property :overview
	property :runtime
	property :poster_path
	property :adult
	property :status

	#Ratings
	property :vote_average
	property :vote_count

	def is_adult?
		adult
	end

	def available?
		status == 'Released' ? true : false
	end

end

app/models/tile.rb
class Tile < Hashie::Dash
	property :image_path
	property :image_text
	property :image_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authorize_user

  def authorize_user

  end


end

app/controllers/carousel_controller.rb
class CarouselController < FragmentController

  def carousel_items
    tiles = CarouselMaker.get_tiles_by_carousel_name(params[:name])
    render :partial => 'common/carousel_items', locals: {tiles: tiles, link: ""}
  end

  def movie_related_carousel_items
    tiles = CarouselMaker.get_movie_related_tiles(params[:name], params[:movie_id])
    render :partial => 'common/carousel_items', locals: {tiles: tiles, link: ""}
  end

end

app/controllers/chart_controller.rb
class ChartController <  ApplicationController

  def index
  end

  def get_data
    @data = [[34, 42], [56, 49]]
  end

end

app/controllers/fragment_controller.rb
class FragmentController < ApplicationController


end

app/controllers/home_controller.rb
# home_controller.rb
class HomeController < ApplicationController
  include HomeHelper

  before_filter :home_index_expire_cache?, :only => [:index]

  caches_action :index,
    :cache_path => :home_index_cache_path.to_proc,
    :expires_in => 90.minutes,
    'max-stale' => 2.hours,
    :public => true

  def index
    @carousels = CarouselMaker.all_carousels_with_some_lazy_loading
    render :index
  end

  def error(code)

  end

end

app/controllers/movies_controller.rb
class MoviesController <  ApplicationController
  include MoviesHelper

  before_filter :movies_show_expire_cache?, :only => [:show]
  before_filter :movies_find_expire_cache?, :only => [:find]

  caches_action :show,
    :cache_path => :movies_show_cache_path.to_proc,
    :expires_in => 90.minutes,
    'max-stale' => 2.hours,
    :public => true

  caches_action :find,
    :cache_path => :movies_find_cache_path.to_proc,
    :expires_in => 90.minutes,
    'max-stale' => 2.hours,
    :public => true

	def show
		id = params[:id]
		logger.info("in the show action")
		@movie = TmdbService.get_movie_by_id(id)
		logger.info("poster: " + TmdbService.get_movie_poster_url_by_size(@movie.poster_path, Settings.tmdb.poster.size.pdp))
		@poster = TmdbService.get_movie_poster_url_by_size(@movie.poster_path, Settings.tmdb.poster.size.pdp)

    @carousels = CarouselMaker.movie_related_carousels_with_some_lazy_loading(id)
	end

	def find
		name = params[:title]
		logger.info("in the find action")
		@movie_tiles = TileMaker.movie_tiles(TmdbService.find_movie_by_name(name))
	end
end

app/helpers/action_cache_helper.rb
module ActionCacheHelper

  # common methods
  def create_action_cache_key(request, opts={})
    params = request.params
    options_hash_string = opts.hash.to_s

    extra_options_key =  "#{I18n::locale}/#{options_hash_string}"
    yield + extra_options_key
  end

  def expire_fragment_view_cache_for_key(ckey, controller=nil)
    controller ||= ActionController::Base.new
    controller.expire_fragment(ckey)
  end

  def fresh_action_cache?
    params[:force_refresh] == "true"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  include ActionCacheHelper

  def home_index_cache_path
    create_action_cache_key(request, {}) do
      "/"
    end
  end

  def home_index_expire_cache?
    expire_fragment_view_cache_for_key(home_index_cache_path, self) if fresh_action_cache?
  end

end

app/helpers/movies_helper.rb
module MoviesHelper
  include ActionCacheHelper

  def movies_show_cache_path
    create_action_cache_key(request, {}) do
      "/movies/#{params[:id]}"
    end
  end

  def movies_show_expire_cache?
    expire_fragment_view_cache_for_key(movies_show_cache_path, self) if fresh_action_cache?
  end

  def movies_find_cache_path
    create_action_cache_key(request, {}) do
      "/movies/#{params[:id]}"
    end
  end

  def movies_find_expire_cache?
    expire_fragment_view_cache_for_key(movies_show_cache_path, self) if fresh_action_cache?
  end

end

app/views/chart/index.haml
= pie_chart [["Football", 10], ["Basketball", 5]]
= line_chart [{name: "Series A", data: {20.day.ago => 2, 4 => 6, "2013-05-07 00:00:00 UTC" => 8}},{name: "Series B", data: {20.day.ago => 5, 6 => 4, "2013-05-07 00:00:00 UTC" => 7}}]

app/views/common/_carousel.html.haml
- if carousel.lazy_load?
	.row.carousel{:'data-lazy-load' => carousel.lazy_load_resource}
- elsif carousel.has_tiles?
	.row.carousel
		=render "common/carousel_items", {tiles: carousel.tiles, link: '' }

app/views/common/_carousel_items.html.haml
.chevron.span.buttons.previous
  %a{:class => 'prev'}
    %i{:class => "fa fa-chevron-left fa-5x"}
.viewport.span8
  %ul.overview
    - tiles.each do |tile|
      - if tile.image_path
        - path = Settings.tmdb.base_url + "/" + Settings.tmdb.poster.size.tile + tile.image_path
        %li.item-tile
          .image-tile
            %span.image
              - if link == "#"
                = image_tag path
              - else
                = link_to image_tag(path), movies_show_path(tile.image_id)
            .info-section
              .caption
                = tile.image_text
.span.chevron.buttons.next
  %a{:class => 'next'}
    %i{:class => "fa fa-chevron-right fa-5x"}

app/views/common/_tile.html.haml
- if tile.image_path
  - path = Settings.tmdb.base_url + "/" + Settings.tmdb.poster.size.tile + tile.image_path
  %li.item-tile
    .image-tile
      %span.image
        - if link == "#"
          = image_tag path
        - else
          = link_to image_tag(path), movies_show_path(tile.image_id)
    .info-section
      .caption
        = tile.image_text

app/views/home/index.html.haml
.center.container
	.hero-unit
		.row
			.span6
				= image_tag "homepage-hero.png"
			.span4
				%h2
					Welcome To NOOK RuBee
				%p
					This is a simple site, using Ruby 2/Rails 4 built with Twitter Bootstrap for look/feel.  The general idea is to have a site heavy with service calls, images and content to demonstrate how to improve performance when the 'odds' are stacked against you.

	- @carousels.each do |carousel|
		%h2
			=t("views.home.index.#{carousel.name}-title")
		%p
			%div{id: "#{carousel.name}"}
				=render "common/carousel", {carousel: carousel}

app/views/layouts/_footer.html.haml
%footer
  %nav.round
    %ul
      %li= link_to "About", "#"
      %li= link_to "Contact", "#"
      / %li= link_to "Check Weather", wungine.root_path
  %p
    Data provided by:
    = link_to image_tag( "http://www.themoviedb.org/images/logos/tmdb-logo-1.png", size: "100x40"), 'http://www.themoviedb.org/'
    = link_to image_tag("http://icons-ak.wxug.com/i/wu/wuLogoUrl.png", size: "62x37"), 'http://www.wunderground.com'

app/views/layouts/_header.html.haml
.navbar.navbar-inverse
  .navbar-inner
    .container
      %a.btn.btn-navbar{:data => {:target => '.navbar-inverse-collapse', :toggle => 'collapse'}}
        .icon-bar
        .icon-bar
        .icon-bar
      .nav-collapse.collapse.navbar-inverse-collapse
        %ul.nav
          %li.active
            = link_to "Home", main_app.homepage_path
          %li
            = link_to "Help", "#"
        .search-bar
          %ul.nav
            %li
              = "Search"
            %li
              = form_tag(main_app.movies_find_path, method: 'GET', class: 'search-form') do
                = text_field_tag 'title', '', class: 'search-box', 'aria-label' => 'Search'

app/views/layouts/application.html.haml
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
    %title= content_for?(:title) ? yield(:title) : "NOOK RBMS"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "//www.google.com/jsapi", "chartkick"
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      %section.round
        - flash.each do |key, value|
          %div{class: "flash #{key}"}= value
        = yield
      = render 'layouts/footer'
    = javascript_include_tag "application"
    = debug(params) if Rails.env.development?

app/views/movies/find.haml
%section.search_results
  %ul.movie_list
    - @movie_tiles.each do |tile|
      = render "common/tile", { tile: tile, link: 'movies' }

app/views/movies/show.haml
.center.container
	.row
		.span12
			%h1
				= @movie.title
	.row
		.span4
			= image_tag @poster
		.span8
			%p
				= @movie.tagline
			%p
				= @movie.overview
			%br
				%b
					= t 'movie.runtime'
					= @movie.runtime
					= t 'movie.duration_unit'

	- @carousels.each do |carousel|
		.row
			.span12
				%h2
					=t("views.movies.show.#{carousel.name}-title")
				%p
					%div{id: "#{carousel.name}"}
						=render "common/carousel", {carousel: carousel}

	/ .row
	/ 	.span12
	/ 		%h2
	/ 			=t('views.movies.show.cast-list-title')
	/ 		%p
	/ 			#actors
	/ 				=render "common/carousel",  {tiles: @cast_list, data_lazy_load: "", link: '#' }
	/ .row
	/ 	.span12
	/ 		%h2
	/ 			=t('views.movies.show.similar-movies-list-title')
	/ 		%p
	/ 			#similar
	/ 				=render "common/carousel", {tiles: @movie_list, data_lazy_load: "", link: 'movies' }